github.com:
    users:
        binku09:
            oauth_token: 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
        zhrnmuron:
            oauth_token: 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
    git_protocol: https
    user: zhrnmuron
    oauth_token: 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
